"""add table

Revision ID: 81367bd3eb5f
Revises: 
Create Date: 2022-04-11 21:26:09.177436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81367bd3eb5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execute_flow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capec_id', sa.Integer(), nullable=True),
    sa.Column('step1', sa.String(), nullable=True),
    sa.Column('step2', sa.String(), nullable=True),
    sa.Column('step3', sa.String(), nullable=True),
    sa.Column('step4', sa.String(), nullable=True),
    sa.Column('step5', sa.String(), nullable=True),
    sa.Column('step6', sa.String(), nullable=True),
    sa.Column('step7', sa.String(), nullable=True),
    sa.Column('step8', sa.String(), nullable=True),
    sa.Column('step9', sa.String(), nullable=True),
    sa.Column('step10', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capec',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('abstraction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('alternate_terms', sa.String(), nullable=True),
    sa.Column('likelihood_of_attack', sa.String(), nullable=True),
    sa.Column('typical_severity', sa.String(), nullable=True),
    sa.Column('related_attack_patterns', sa.String(), nullable=True),
    sa.Column('execution_flow', sa.String(), nullable=True),
    sa.Column('prerequisites', sa.String(), nullable=True),
    sa.Column('skills_required', sa.String(), nullable=True),
    sa.Column('resources_required', sa.String(), nullable=True),
    sa.Column('indicators', sa.String(), nullable=True),
    sa.Column('consequences', sa.String(), nullable=True),
    sa.Column('mitigations', sa.String(), nullable=True),
    sa.Column('example_instances', sa.String(), nullable=True),
    sa.Column('related_weaknesses', sa.String(), nullable=True),
    sa.Column('taxonomy_mappings', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_flow'], ['execute_flow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capec')
    op.drop_table('execute_flow')
    op.drop_table('definition')
    # ### end Alembic commands ###
