"""update fixture definition

Revision ID: a8741ff87139
Revises: 81367bd3eb5f
Create Date: 2022-04-11 21:26:41.192469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text, MetaData, Table

from datetime import datetime
# revision identifiers, used by Alembic.
revision = 'a8741ff87139'
down_revision = '81367bd3eb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    insert_all_data()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def insert_config(data):
    conn = op.get_bind()
    app_data = conn.execute(
        "SELECT * FROM definition WHERE id = {}".format(data.get("id"))
    )
    if app_data.first():
        query_text = text(
            "UPDATE definition SET id = :id, key = :key, value = :value, source = :source, created_date = :created_date"
            " WHERE id = :id"
        )
        conn.execute(
            query_text,
            {
                'id': data.get("id"),
                'key': data.get("key"),
                'value': data.get("value"),
                'source': data.get("source"),
                'created_date': data.get("created_date"),
            }
        )
    else:
        meta = MetaData(bind=op.get_bind())
        meta.reflect(only=('definition',))
        some_table_tbl = Table('definition', meta)
        op.bulk_insert(
            some_table_tbl,[data]
        )

def insert_all_data():
    data = json_data()
    for single_data in data:
        insert_config(single_data)

def json_data():
    data = [
        {
            "id":1,
            "key":"cve",
            "value":"CVE, short for Common Vulnerabilities and Exposures, is a list of publicly disclosed computer security flaws. When someone refers to a CVE, they mean a security flaw that's been assigned a CVE ID number. Security advisories issued by vendors and researchers almost always mention at least one CVE ID. CVEs help IT professionals coordinate their efforts to prioritize and address these vulnerabilities to make computer systems more secure.",
            "source":"https://www.redhat.com/en/topics/security/what-is-cve",
            "created_date":datetime.now()
       },
       {
            "id":2,
            "key":"cwe",
            "value":"CWE™ is a community-developed list of software and hardware weakness types. It serves as a common language, a measuring stick for security tools, and as a baseline for weakness identification, mitigation, and prevention efforts.",
            "source":"https://cve.mitre.org/",
            "created_date":datetime.now()
       },
       {
           "id":3,
           "key":"cvss",
           "value":"The Common Vulnerability Scoring System (CVSS) is an open framework for communicating the characteristics and severity of software vulnerabilities. CVSS consists of three metric groups: Base, Temporal, and Environmental. The Base metrics produce a score ranging from 0 to 10, which can then be modified by scoring the Temporal and Environmental metrics. A CVSS score is also represented as a vector string, a compressed textual representation of the values used to derive the score. Thus, CVSS is well suited as a standard measurement system for industries, organizations, and governments that need accurate and consistent vulnerability severity scores. Two common uses of CVSS are calculating the severity of vulnerabilities discovered on one's systems and as a factor in prioritization of vulnerability remediation activities. The National Vulnerability Database (NVD) provides CVSS scores for almost all known vulnerabilities.",
           "source":"https://nvd.nist.gov/vuln-metrics/cvss",
           "created_date":datetime.now()
       },
       {
           "id":4,
           "key":"capec",
           "value":"The Common Attack Pattern Enumeration and Classification (CAPEC™) effort provides a publicly available catalog of common attack patterns that helps users understand how adversaries exploit weaknesses in applications and other cyber-enabled capabilities.",
           "source":"https://capec.mitre.org/about/index.html",
           "created_date":datetime.now()
       }

    ]
    return data